### ISSUE TITLE
UX: Date picker

### ISSUE THREAD

**Issue by Tomucha** [GoogleDeveloperExperts/experts-app-web#101]
<input type="date"> isn't very friendly, date picker would be nice.

**Comment by CesarAntonNBCU** [comment]
@Tomucha it uses the default Material input, the date picker goes at the right of the line.

Perhaps we should add a tool tip to point it out?

![image](https://cloud.githubusercontent.com/assets/20321227/18723522/e3d40c0e-8006-11e6-9935-1df9ac5f1262.png)

Thanks

**Comment by Tomucha** [comment]
Well ... I didn't notice it ... like ... at all :-)
Maybe make the whole input shorter? (max-width: 15em or something) Dropdown icon is too far on the right.

(Or ignore me competely)

**Comment by reicek** [comment]
The fact you didn't saw it points that it needs some fine tuning @Tomucha 

+1 to making it shorter, maybe right after the 'yyyy'. I'll get that ASAP.
