### ISSUE TITLE
Step 2 (Product Groups) UI for tags isn't ideal

### ISSUE THREAD

**Issue by alexismp** [GoogleDeveloperExperts/experts-app-web#103]
When reporting an activity, selecting the product group tag(s) is not ideal:
- All caps tags are hard to read (true also in other parts of the app)
- tags should be auto-completed or pre-populated based on the GDE's area of expertise

**Comment by LostInBrittany** [comment]
This one is going to be redone rather quickly, as several people have given the same feedback :)

**Comment by justinribeiro** [comment]
The product screen has changed a bit with the addition of PR #102 (notably filter and even sized buttons, see screenshot) which should make it a little easier to handle.

In terms of autocompleting selections, I think works in principle but is also somewhat problematic (multi-area GDEs, sub-type products in the same brand category will still require selection). I hesitate to say let's implement this in the current MVP (account doesn't have a one-to-many mapping to ProductGroup tags).

![image](https://cloud.githubusercontent.com/assets/643503/18797828/a8ba8970-8184-11e6-9ad5-cf4e7303c88a.png)

**Comment by LostInBrittany** [comment]
So for now we can consider this one complete?

**Comment by justinribeiro** [comment]
Yes. I've captured the other req so let's close this for now.
