### ISSUE TITLE
tags should all have explanations

### ISSUE THREAD

**Issue by alexismp** [GoogleDeveloperExperts/experts-app-web#104]
While Product Group tags can be pretty self-explanatory, those used for Activity Groups/Types are not, at least not to me (e.g. what do #OPENSOURCE or #COMMUNITYEVENTS mean?). 
I would like to suggest that we offer hover-over explanation on each tag (tooltip).

**Comment by LostInBrittany** [comment]
No problem with adding tooltips, but I need these tooltips' text to be in the datastore

. @patt0 what do you think? Can you add a description for Activity Groups/Types ?

**Comment by justinribeiro** [comment]
@LostInBrittany `ActivityTypes` have a `description` field (see screenshot). Possibly we don't have it exposed in the API, I'll have to check.

![image](https://cloud.githubusercontent.com/assets/643503/18797764/563b440a-8184-11e6-8cac-b7b7ca7a02cf.png)

**Comment by patt0** [comment]
It is exposed, just needs to be used appropriately.

Patrick Martinent

**Comment by LostInBrittany** [comment]
Yes, I saw it last Saturday why working on it :)

It will be done in next iteration, that corrects all the bugs I assigned
myself last Fridaty,  for tonight :)
