### ISSUE TITLE
"Activity link" needs to be smarter

### ISSUE THREAD

**Issue by alexismp** [GoogleDeveloperExperts/experts-app-web#105]
IMO reporting should start with the activity link and a lot can be derived just from that link.
You should not have to chose "twitter", "medium" or "Youtube" from a drop down list if you've given the URL already

**Comment by LostInBrittany** [comment]
This one is a bit trickier, as I'm not sure if it should be done front-side (I don't like the idea) of backend-side (and then it asks for new services by @patt0 )

I am not sure if it will be ready for 2.0.0-Beta...

**Comment by justinribeiro** [comment]
> IMO reporting should start with the activity link and a lot can be derived just from that link

I agree (and we've had the discussion of this feature on the weekly call previously). I've captured this as a future item, but currently this is outside the MVP scope of requirements for this version. 

Let's table this for post-Beta implementation.
