### ISSUE TITLE
Make location/date easier to fill out (and possibly optional)

### ISSUE THREAD

**Issue by alexismp** [GoogleDeveloperExperts/experts-app-web#106]
Date should be pre-filled to current day and location to GDE's default location.
Location should be checked against a reference list to avoid duplicates or typos.
Also location only makes sense for in-person contributions, no?

**Comment by LostInBrittany** [comment]
We had a discussion about location a while ago, how about (for example) full online activities.

I think we need to speak again about it. I agree with Alexis...

**Comment by justinribeiro** [comment]
> Date should be pre-filled to current day

Probably not. Based on cursory survey, GDE's don't often submit data the same day it's completed.

> and location to GDE's default location.
> Also location only makes sense for in-person contributions, no?

Let's make City/Country optional for now to resolve that case.

**Comment by LostInBrittany** [comment]
For now I'm going to make location optional
After the MVP we will see about the checking against a reference list to avoid duplicates or typos.

For the date, prefilling it with current date is better than leaving it empty, going to make it too, and we will test...

**Comment by LostInBrittany** [comment]
Location is optional now
