### ISSUE TITLE
Product Groups tags should be dynamic be populated based on previous activity and/or GDE field or expertise

### ISSUE THREAD

**Issue by alexismp** [GoogleDeveloperExperts/experts-app-web#110]
I'm a Cloud GDE and of all Product Groups tags offered #CLOUDPLATFORM is the only one (out of 44!) that fits and it's too broad.
Cloud is likely to have at least as many tags as products in the platform (dozens).
I should also be able to create my own tags with some admin deduplicating tags

**Comment by justinribeiro** [comment]
While I agree the range of tags does not match the growing ecosystem of Google products that experts may be working on, in my experience in building tools for reporting in the past, this results in two effects:
1. Dynamic tags create fractured data. One persons' tags are not another's and this causes additional work when writing reports trying to group areas correctly.
2. User indecision. No one likes filling in forms and free form tag inputs are horrible productivity drags (I have implemented this a lot, and it's the first thing people complain about).

So how do we get around this? Looking at the current `ProductGroup` entity, we have some options.
1. Implement the sane default and filter on `Category`. This is particularly useful to Marketing, Product Strategy, and UI/UX experts as the bulk of product groups are in of the type `tech`.
2. Condense `tech` type inline with both the current expert program categories and the product lines.
3. Utilize either the existing `product` field and filter and display relevant content associated in the dataset, or we could use the `so_tags` field array associated to records and display that for selection.

For 1, we can re-use some of our existing fields on the `Account` entity to do this. For 2, we can clean up what's in `ProductGroup`. For 3, we should probably discuss this more before we implement this (as there may be a better way that I'm not seeing).

I've put a hold label on this for now; let's discuss this on the call tomorrow and see what we think we can slip in before we move the current milestone into PROD.

**Comment by patt0** [comment]
We did not talk about this :( I had not seen this email.

There seems to be an imbalance for sure.

We can easily add tags to the master list that syncs with the backend and
they will appear in the app.

I am sharing the master list with you Alexis so you can look at it and we
can further talk about it and push things in before we release on Monday.

Best

Patrick Martinent

**Comment by alexismp** [comment]
> Dynamic tags create fractured data

That's why we need to be able a de-dup / cleanup feature and I'm happy to use it regularly.
We have new products every months and I need to be able to query by product. A single tag for Cloud is useless for me unfortunately (and it should probably be added by default for Cloud GDEs anyway).

Instead I need to be able to query the system for "Machine learning activities in Asia for the past 2 months" and "machine learning" needs to be an aggregate of products and technologies, not only a tag of its own.

> free form tag inputs are horrible productivity drags

not with proper completion I don't think

I really think the tool should not present any tag but offer instead the user to type a list of auto-completed or new tags on a single line.

**Comment by justinribeiro** [comment]
@alexismp We're having a meeting next Wednesday to discuss the tag situation and available implementation options. You should see an email from Nat on the details.
