### ISSUE TITLE
Certain ActivityDetail links need a no-URL option

### ISSUE THREAD

**Issue by justinribeiro** [GoogleDeveloperExperts/experts-app-web#129]
In certain reported edge cases since v2 launched, ActivityDetail links may be need to be empty but still report impact. Examples include:
- one-to-one repeated mentoring
- WIP writing for large projects (books or documentation that have no public release or tracker)
- GDE program activities (interviews and reviews)

The validation (among other things) currently does not take these edge cases into account.

**Comment by stp-ip** [comment]
To add a few use-cases:
* foss maintainer discussions
* foss user help/discussions
* ecosystem feedback and outreach (aka how does GCP product X stack up to Y - might even be discussed with Y's actual team)
* hallway track related discussions, mentoring, bug reports etc.
