### ISSUE TITLE
activity_detail sometimes not reset on subsequent link submits

### ISSUE THREAD

**Issue by justinribeiro** [GoogleDeveloperExperts/experts-app-web#130]
The is a case where the `paper-dropdown-menu` which houses activity_detail link types will sometimes not hold it's state or reset. In this case, you end up with a "it's cool, I'm valid" but not data (which can cause gaps).

This is a very specific edge case that's only occurred once as far as I can tell, but it annoys me so I'm going to fix it.

**Comment by Nevraeka** [comment]
I am having this issue consistently where I have to refresh the page for every activity post

**Comment by justinribeiro** [comment]
@Nevraeka I'll move this up into the next patch release.

**Comment by Nevraeka** [comment]
muchos gracias amigo

**Comment by thangman22** [comment]
Some one fix it?
