### ISSUE TITLE
Stuck on "Completing Data Save  Please wait, we're inserting your data..."

### ISSUE THREAD

**Issue by alexismp** [GoogleDeveloperExperts/experts-app-web#133]
I tried saving dummy datajust minutes ago and have had the "Completing Data Save, Please wait, we're inserting your data..." dialog up for several minutes now

**Comment by patt0** [comment]
Alexis, you do not have an account on the platform. So in fact you should not have been able to login if you had the latest version loaded. Let me know if you want me to add you in the backend.

**Comment by alexismp** [comment]
Yes, please add this gmail account (alexis.mp@gmail.com) as a Cloud GDE.
thanks.

**Comment by patt0** [comment]
done, please refresh.

**Comment by cfjedimaster** [comment]
I got this today. I have an account - I had saved a few activities already - and now I'm getting the same issue.
