### ISSUE TITLE
Dialogs should be scrollable for small screens.

### ISSUE THREAD

**Issue by Scarygami** [GoogleDeveloperExperts/experts-app-web#134]
Otherwise data entry is impossible on phones:
![screenshot](https://cloud.githubusercontent.com/assets/809528/19479057/444dc45a-9545-11e6-8509-fbf6df3122e8.png)

**Comment by abraham** [comment]
You need one of these:

<img src="https://i.imgur.com/iL1MR.jpg" height="400">

**Comment by Rumyra** [comment]
I'm also finding this on my macbook - screen res 1280 x 800

Looking like it's a combination of height:100vh on outer and overflow:hidden on dialogues - I simply can't see the submit buttons. Hacking every stage is a pain too.

I would pull, fiddle and pr but I am literally just about to fly to SIN for hols - best excuse EVER (soz) ☺️

**Comment by Omranic** [comment]
@justinribeiro @Scarygami Just a friendly reminder, this issue isn't limited to small screens. It's available on all screen sizes whenever the list is longer than screen hight.

**Comment by justinribeiro** [comment]
Appreciate the reminder. The dialog's don't use `paper-dialog-scrollable` which is the main issue (device agnostic).

**Comment by tasomaniac** [comment]
I am also struggling to submit because of this. I have 13 inch MacBook. I believe it should be fine. Here is the screen I stuck.

![image](https://cloud.githubusercontent.com/assets/763339/22979550/1731738a-f397-11e6-94ae-ce044b2fdc4f.png)

**Comment by LostInBrittany** [comment]
I've just deployed a version that add `paper-scrollable-dialog` to the _create activity_ and _create activity detail_ screens, it should solve the problem.

Can you please test and tell me if it's ok for you, and I'll close this issue? :)
