### ISSUE TITLE
App renaming/Rebranding

### ISSUE THREAD

**Issue by SmokyBob** [GoogleDeveloperExperts/experts-app-web#14]
The GDE Program have a bigger scope now and it's called Google Experts.

[Soon](https://github.com/GoogleDeveloperExperts/gde-app-backend/issues/3) we'll have Experts from other Area of expertise, not only Tech/Developer, make sense to rename the App to "Experts Tracking"

Other related things to change:
- Use the new logo
- Change the app url (expertstraking.appspot.com ?)
- Change GDEAccess, Title, etc to Google Experts

Small Nice to have thingys (might be worth creating separated issues, but adding here for centered discussion):
- rename the element `gde-signin` to `expert-signin`
- rename property `isGde` to `isExpert`

**Comment by patt0** [comment]
+1 to switch the app url reflect the new branding

**Comment by Scarygami** [comment]
Also change the name of the repos :)

**Comment by SmokyBob** [comment]
mmm seemed like I forgot something :D
Doing in a bit

**Comment by SmokyBob** [comment]
Renamed web and backend.
Just to make full circle, we should add a backend endpoint named `expertstracking` and retire the `gdetracking` when the new version goes live for everyone
