### ISSUE TITLE
[Feature Request] Edit Impact

### ISSUE THREAD

**Issue by Scarygami** [GoogleDeveloperExperts/experts-app-web#142]
For several activity links the impact changes over time after the initial activity.

I like to record my activities as they happen, so I don't forget about them, so most activity links won't have reached significant impact yet. In the old tracker I used to go back in after a while and adjust the impact accordingly, but this is not possible with the new tracker.

As a workaround I can remove a link and add it again with the updated numbers, but being able to directly edit the impact would be nicer :)

**Comment by justinribeiro** [comment]
Actually this is a bug; the edit icon is missing in the pushed build for some reason (which was not the case previously). You can indeed edit impact...it's just hiding. :-)

![image](https://cloud.githubusercontent.com/assets/643503/19611607/4e9388b0-9797-11e6-8eb3-e8ce31734283.png)

I'm a day behind on the v2.0.5 so I'm going to slip this in as a patch.
