### ISSUE TITLE
Can't edit profile

### ISSUE THREAD

**Issue by holgereggert** [GoogleDeveloperExperts/experts-app-web#144]
Hi there,
I can't edit my profile, or rather I can't save my edits. There are no buttons to save anything and it doesn't auto-save, everything I enter is gone after a reload. Is this just me? Or are you aware of this already?
(I'm on latest Chrome and latest macOS.)
Cheers, Holger.

**Comment by justinribeiro** [comment]
Let's patch this while we work out UI details in v2.0.7.

**Comment by LostInBrittany** [comment]
I'm tracking this one later this week, I think there is a missing button...

**Comment by LostInBrittany** [comment]
I seem unable to reproduce that in Chrome on both Linux and Windows...

But I see the issue on Firefox, so I'm going to track the bug...

FWIW, when editing something in your profile, you should see a green tick mark at the right of the field, allowing you to save:
![image](https://cloud.githubusercontent.com/assets/726476/23214219/2b821534-f90e-11e6-9c52-db7f134d6302.png)

**Comment by LostInBrittany** [comment]
Deployed, I see the icons in Chrome and Firefox on Windows and Linux, and on Edge on Windows

**Comment by abraham** [comment]
I'm seeing the buttons now in Chrome.
