### ISSUE TITLE
Activity Category  - Add Non Google or "Other" category

### ISSUE THREAD

**Issue by jefBinomed** [GoogleDeveloperExperts/experts-app-web#145]
I do somes activities that are not really link to any google technology but that is a part of my job as GDE. I gave a talk about "Public Speaking" which is a kind of "insperationnal" or "other" category and for now i don't really know which category I choose.

So can you please add this new category ?

**Comment by justinribeiro** [comment]
Typically if it isn't related to a technology or product group, then it may not fit the criteria (as you are a GDE in a product area and product groups have different goals for GDE's than others). However, the decision to add categories lies with @avedave and @NatPer. I defer to them.

**Comment by jefBinomed** [comment]
Hi Justin, I'm not agree with you becase for example, i gave a lot of talk no how to help people to becomes speakers. I think helping people to share knowledge and helping them to share google content is also a part of our job as GDE .

@NatPer, @avedave, what did you think about this ?
