### ISSUE TITLE
iron-icon vs iron-icons confusion and errors

### ISSUE THREAD

**Issue by Splaktar** [GoogleDeveloperExperts/experts-app-web#152]
Many pages include:
```
<link rel="import" href="../../bower_components/iron-icons/iron-icons.html">
```

But Bower does not, it only has:
```
    "iron-icon": "PolymerElements/iron-icon#^1.0.0",
    "iron-iconset-svg": "PolymerElements/iron-iconset-svg#^1.0.0",
```

This leads to the following in the Chrome console
```
GET http://localhost:8080/bower_components/iron-icons/iron-icons.html 404 (Not Found)
```

Should the `iron-icons` import be removed and `icon-iconset-svg` be used instead? 
Or should `iron-icons` be added to `bower.json`?

**Comment by justinribeiro** [comment]
Resolved in https://github.com/GoogleDeveloperExperts/experts-app-web/commit/d8cd5fc196b04a917dd4428cd3b4b5be6cfc862a
