### ISSUE TITLE
Activitites have no default ordering

### ISSUE THREAD

**Issue by riggaroo** [GoogleDeveloperExperts/experts-app-web#153]
When viewing data on the dashboard, it is difficult to see what was entered last as the content is not ordered by anything.

My suggestion is to order by latest date first or even better allow users to order by any of the columns in the table.

**Comment by justinribeiro** [comment]
Note to self: check if this is the bind or the query.

**Comment by LostInBrittany** [comment]
I had prepared everything to do the sorting on the list, and I forgot to add it to the first release, I'll do it later this week.

**Comment by LostInBrittany** [comment]
I will deploy this version later today

**Comment by LostInBrittany** [comment]
Deployed, sorting is done and default sorting is by date (most recent activity first)

**Comment by riggaroo** [comment]
Hi, I might be hitting a bug, but when i login an activity from 2016 is shown first. When I click the drop down arrow, the ordering works from oldest to newest but not from newest to oldest it seems. 
See attached screenshot. 
<img width="748" alt="screen shot 2017-02-22 at 7 33 20 pm" src="https://cloud.githubusercontent.com/assets/9973046/23224193/fe79c604-f935-11e6-8592-d8c7acc32378.png">

**Comment by LostInBrittany** [comment]
ouch, it should't do that!

have you tried to sort with other columns? do they work?
I'm going to put some logs on the sorting to... ehem... _sort_ the problem (pun intended :) )
