### ISSUE TITLE
"Submit" button for activity entry is off-screen, unaccessible from tab-focus.

### ISSUE THREAD

**Issue by kanawish** [GoogleDeveloperExperts/experts-app-web#154]
Had to resize browser to get access to submit button.

**Comment by justinribeiro** [comment]
I believe this is a duplicate of #134 due to the lack of scrollable region. I'll check.

**Comment by justinribeiro** [comment]
Resolved in https://github.com/GoogleDeveloperExperts/experts-app-web/releases/tag/2.0.7
