### ISSUE TITLE
Metrics for conferences

### ISSUE THREAD

**Issue by kanawish** [GoogleDeveloperExperts/experts-app-web#155]
It's unclear how to report 'viewing public' and 'conference size' from the URL focused impact points.

**Comment by justinribeiro** [comment]
Conference size isn't a tracked metric; it's about your impact and the folks you speak to and the action around that. Consider a typical conference appearance. You may have activity links that look something like this:

```Activity link: My Talk @ Org Website
Activity link: Tweet about event
Activity link: Slides
Activity link: Github Repo Code sample
Activity link: Tweet after event target slides+code
Activity link: Tweet about event by Org
Activity link: Tweet about event by you Product Team
Activity link: Article about your talk @ Third Party Publication
```

In terms of say `Activity link: My Talk @ Org Website` this would be a common target link to say what your direct impact was (how many people you talked to in the room).

There are a lot of edge cases even in that; what if there was streaming? What if there was a video posted later? You could attach the view count as direct impact with the stream/video link for instance.

At the end of the day, URLs are means of partial validation (and possible newsletter / sharing / promo content). We're taking your word of the size of your crowd and the impact that you show.

**Comment by kanawish** [comment]
It might be worth creating an action item to clarifying the conference angle. 

Forcing a URL on every 'impact' entry makes for a situation where we deny impact on anything that happens 'offline'. Think of people doing office hours, or doing mentoring. Most of the time it's possible to attach some sort of organizational link, I guess. But again, that could made clearer.

**Comment by justinribeiro** [comment]
Agreed; we have those changes slated as part of #129 .

**Comment by kanawish** [comment]
awesome, thank you!
