### ISSUE TITLE
webcomponents-lite.min.js is missing

### ISSUE THREAD

**Issue by Scarygami** [GoogleDeveloperExperts/experts-app-web#158]
Which means the app isn't usable if you are using (are forced to use) browsers without native support.

**Comment by LostInBrittany** [comment]
This one is a simple problem, it should be added to the `polymer.json` as `includeDependencies`. I'm doing it later this week.

**Comment by LostInBrittany** [comment]
It should be corrected, I will deploy a version that corrects this one and other bugs later today. Closing it now, I will post a message here as soon as the deployment is done.

**Comment by LostInBrittany** [comment]
Deployed, `https://expertstracking.appspot.com/bower_components/webcomponentsjs/webcomponents-lite.min.js` is available now

**Comment by EloyClemente** [comment]
Thanks man!!!
