### ISSUE TITLE
#organize button missing title text

### ISSUE THREAD

**Issue by abraham** [GoogleDeveloperExperts/experts-app-web#161]
<img width="949" alt="screen shot 2017-02-12 at 07 52 56" src="https://cloud.githubusercontent.com/assets/3341/22862637/5e4b3356-f0f8-11e6-974f-fc429223efd2.png">

E.g. #bugreport has `Report a bug/crash/security issue on a Google API` as a title when you mouseover.

**Comment by justinribeiro** [comment]
Datastore updated.
