### ISSUE TITLE
Default ordering not applied for date

### ISSUE THREAD

**Issue by gnomeontherun** [GoogleDeveloperExperts/experts-app-web#167]
This is the default ordering I'm seeing on my account. It shows 'date' but does not sort by date until it is clicked.

![image](https://cloud.githubusercontent.com/assets/79500/24130442/7c9e3314-0db6-11e7-8457-963420c56a5c.png)

**Comment by abraham** [comment]
Even after clicking it's not sorting correctly.

![screen shot 2017-03-29 at 16 04 17](https://cloud.githubusercontent.com/assets/3341/24476577/6b28f170-1499-11e7-9f70-43e3153e2214.png)

**Comment by LostInBrittany** [comment]
I'm looking at it this weekend.
Does sorting by other criteria work for you?

On Wed, Mar 29, 2017 at 11:04 PM, Abraham Williams <notifications@github.com

**Comment by gnomeontherun** [comment]
It appears to work fine for my list of events once I click, regardless of what criteria is used. Just the default is wrong for me.

**Comment by Scarygami** [comment]
Issue is that the sort function is returning a boolean value.

The Array sort function should return a value < 0 if the first item is supposed to come first and a value > 0 if the second item is supposed to come first (or 0 if they are equal).

I can send a PR to fix this behaviour (unless @justinribeiro is already working on it).

**Comment by LostInBrittany** [comment]
O.K., there is still a problem in date... I have one hour this noon, I will fix it once and forever, this bug is really bothering, sorry all

**Comment by LostInBrittany** [comment]
O.K., that time it was a build problem, issue is indeed solved in local
Rebuilding, redeploying and closing ...

**Comment by LostInBrittany** [comment]
There was a problem with the sort function, it was never called with the initial values.

Now it's working for me on Firefox and Chrome. Please reopen if you still experience any problem.
