### ISSUE TITLE
Suggestion: Introduce Tango and Daydream as new product groups

### ISSUE THREAD

**Issue by AlexKorovyansky** [GoogleDeveloperExperts/experts-app-web#177]
I'm speaking about Tango and Daydream in the community. I'm sure that I'm not single GDE doing that. So for me it looks rational to have `#Tango` and `#Daydream` as product groups.

<img width="722" alt="image 2017-06-09 at 12 29 55 pm" src="https://user-images.githubusercontent.com/479961/26963643-829248c6-4d0f-11e7-8386-f6fccd710fe3.png">

**Comment by patt0** [comment]
Done


Patrick Martinent

**Comment by AlexKorovyansky** [comment]
Awesome! Thanks!
