### ISSUE TITLE
Ability to export all your activity data to JSON / CSV / whatever

### ISSUE THREAD

**Issue by urish** [GoogleDeveloperExperts/experts-app-web#178]

**Comment by urish** [comment]
Do you guys need any help with implementing this?

**Comment by patt0** [comment]
We have that ... We are not sure how useful it is ... Let's work through
your use case in Krakow?

**Comment by urish** [comment]
Thanks for the reply Patrick, basically, my use case is to have a full backup of my activity data (including the links). I believe other experts would also be interested in such feature (at least the ones who up voted this issue so far)

Is there a backend API call that returns all this data at once?
