### ISSUE TITLE
Update validator for activity date

### ISSUE THREAD

**Issue by justinribeiro** [GoogleDeveloperExperts/experts-app-web#179]
There is a case where the date is still getting mucked (e.g. 0007, 1985, 1987) which is still causing the issue reported and tracked as #175. Needs to be further checked.

**Comment by abraham** [comment]
Is this users entering incorrect dates? Are you looking to validate the date on the client with something like the following?

```
const activityDate = new Date('2018-02-01');
new Date('2015-01-01') < activityDate && activityDate < new Date();
```
