### ISSUE TITLE
Can't post any activities. Error in API

### ISSUE THREAD

**Issue by sjg** [GoogleDeveloperExperts/experts-app-web#190]
I've hit a bug where currently I can't post any activities in the app.  No previous activities are listed on the page and I can't post any new activities on the app.

On the Javascript console I get:

`Failed to load resource: the server responded with a status of 503 ()`

which the JSON endpoint it's trying to hit says on https://elite-firefly-737.appspot.com/_ah/api/expertstracking/v2.0/activityMaster/activityMaster?limit=100&email=steven.james.gray%40gmail.com&order=-date:

`{
  "error": {
    "errors": [{
      "domain": "global",
      "reason": "backendError",
      "message": "Internal Server Error"
    }],
    "code": 503,
    "message": "Internal Server Error"
  }
}`

**Comment by jfedor** [comment]
same I just opened a dupe issue :(
