### ISSUE TITLE
Experts API

### ISSUE THREAD

**Issue by tasomaniac** [GoogleDeveloperExperts/experts-app-web#39]
There is an unofficial GDE Directory API we use in https://github.com/gdg-x/frisbee application. 

https://gde-map.appspot.com/gde/list

That API is old and does not remove ex-gde's. 

Is there a possibility to build a GDE Directory API where it is public and outputs the current active GDEs with their information.

**Comment by Scarygami** [comment]
You mean something like https://omega-keep-406.appspot.com/_ah/api/gdetracking/v1.0b2/account/account ? ;)

**Comment by tasomaniac** [comment]
Actually I saw that link when I search through the source code. :)

I will try to integrate with it. Does it have options to filter the product_group?

**Comment by Scarygami** [comment]
Not at the moment, but we could adjust the API accordingly :)

**Comment by SmokyBob** [comment]
Be advised that product_group is going away really soon ([ref](https://github.com/GoogleDeveloperExperts/experts-app-backend/issues/16))  and will be replaced by area of expertise.

**Comment by tasomaniac** [comment]
Any filter in the Api will do it.

**Comment by tasomaniac** [comment]
An explanation about the close would be nice for documenting here. Thanks.

**Comment by reicek** [comment]
Sure @tasomaniac 

This issue it's related to the GDE Tracking App v1, we are currently working on v2 and we are about to launch it in a few weeks, so all issues related to v1 that no longer applies were closed.

FYI, v2 has been fully recoded and redesigned from the ground-up, back-end and front-end are completely new. You can take a look on the **Polymer branch**.

New version it's way faster, mobile friendly and extremely easy to use.

As soon as it ready and fully tested there will be an official announce.

Thank you for you keeping an eye on the project, best regards.

**Comment by tasomaniac** [comment]
Thanks for the detailed reply. But this issue is not related to any version. This is just asking for an api to query Experts.

**Comment by reicek** [comment]
@tasomaniac ohh you can use our endpoint for that, it will be kept updated =)

GET https://elite-firefly-737.appspot.com/_ah/api/gdetracking/v1.0b2/account/account

You can test round the API explorer:

 https://apis-explorer.appspot.com/apis-explorer/?base=https://elite-firefly-737.appspot.com/_ah/api#p/gdetracking/v1.0b2/

Best,

**Comment by patt0** [comment]
We probably need to update the API version number before going live unless
we swap production and staging.

**Comment by tasomaniac** [comment]
Thank you very much. These endpoints are invaluable :)
