### ISSUE TITLE
Unable to enter the date for an activity

### ISSUE THREAD

**Issue by jackfranklin** [GoogleDeveloperExperts/experts-app-web#40]
Hello!

When I go to add an activity, and want to change the date, I try to do so by selecting the date input box and trying to type the new date in.

However, I am able to delete the existing date but then unable to change it or type anything in. Whenever I try to type a number in, nothing appears in the input box. It feels like there's a pop up that should be appearing to help pick the date but that's not happening.

Cheers,

Jack

**Comment by SmokyBob** [comment]
The Activity Date it's a "standard" text input, no date picker (there was no element for that and I was to lazy to write one from scratch).
The Activity Date should be the only date editable, and the format validation is done only when hitting the save button.

I've tried to replicate on Chrome Dev v46.0.2467.2 and I'm not able to reproduce the issue.

Can you provide other information that can help identifying what could be the cause, like:
- the browser used
- can you any error in the browser console 
- is this the first activity ever created? (the list of activities it's completely empty)
- can you provide a screenshot of the issue happening?

**Comment by jackfranklin** [comment]
False alarm, it was Vimium messing up :( Sorry!
