### ISSUE TITLE
App icons for different sizes

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleDeveloperExperts/experts-app-web#62]
I recently tried `App Toolbox` by Polymer team which has prefered icon sizes for `manifest.json` as these:
- 32x32 png
- 128x128 svg
- 144x144 png
- 192x192 svg
- 384x384 svg

We should update app with these.

**Comment by VikramTiwari** [comment]
With https://github.com/GoogleDeveloperExperts/experts-app-web/pull/61/commits/4ca8d977c5cb2197f12a0c77622056088106c78c I have added icons for recommended sizes. But those icons are not in correct format. Could totally leave it like that, or can replace with correct format icons. As it seem fit.

**Comment by reicek** [comment]
Thanks @VikramTiwari , we are currently rebuilding the whole app to v3, fully redesigned and rebuilt from the ground up. We will be **launching around 13/06/16**.

We will be taking this into account for the icon sizes.
