### ISSUE TITLE
Implement Google Sign-In flow

### ISSUE THREAD

**Issue by justinribeiro** [GoogleDeveloperExperts/experts-app-web#64]
Composes of requirements 1 and 2:
1. The application shall allow only whitelisted users to log into the system.
2. The application shall use Google Sign-In as the authentication mechanism.

**Comment by reicek** [comment]
Saved for the last since it's the easiest part to implement. Will work on it after completing issue #65

**Comment by reicek** [comment]
I'll leave this open in case someone can take it =)

**Comment by LostInBrittany** [comment]
Done :)
