### ISSUE TITLE
Implement Add Activity workflow

### ISSUE THREAD

**Issue by justinribeiro** [GoogleDeveloperExperts/experts-app-web#67]
Composes of requirements 9, 10, 11, 12, 13, 14:

<ol start="9">
  <li>The application shall define the following fields for an activity for user input:</li>
</ol>

<table>
  <tr>
    <td>Field</td>
    <td>Type</td>
    <td>Validate</td>
    <td>Description</td>
  </tr>
  <tr>
    <td>title</td>
    <td>ndb.StringProperty()</td>
    <td>required</td>
    <td>Title of the activity</td>
  </tr>
  <tr>
    <td>description</td>
    <td>ndb.StringProperty()</td>
    <td>required</td>
    <td>Overview of activity</td>
  </tr>
  <tr>
    <td>type</td>
    <td>ndb.StringProperty()</td>
    <td>required</td>
    <td>General activity type, list from XYZ </td>
  </tr>
  <tr>
    <td>city</td>
    <td>ndb.StringProperty()</td>
    <td>required</td>
    <td>City</td>
  </tr>
  <tr>
    <td>country</td>
    <td>ndb.StringProperty()</td>
    <td>required</td>
    <td>Country</td>
  </tr>
  <tr>
    <td>date</td>
    <td>ndb.DateProperty()</td>
    <td>required</td>
    <td>Activity date profile name</td>
  </tr>
</table>

<ol start="10">
  <li>The application shall allow a user to delete a master activity record.
  <ol><li>The application shall cascade to delete any associated supporting child records for an activity.</li></ol>
  </li>
  <li>The application shall allow a user to update a master activity record’s data.</li>
  <li>The application shall define the following fields for a supporting child record for user input:</li>
</ol>

<table>
  <tr>
    <td>Field</td>
    <td>Type</td>
    <td>Validate</td>
    <td>Description</td>
  </tr>
  <tr>
    <td>type</td>
    <td>ndb.StringProperty()</td>
    <td>required</td>
    <td>General support record type, list from XYZ, allow only one per type.</td>
  </tr>
  <tr>
    <td>url</td>
    <td>ndb.StringProperty()</td>
    <td>required</td>
    <td>URL where exists for this type</td>
  </tr>
  <tr>
    <td>metric_reached</td>
    <td>ndb.IntegerProperty()</td>
    <td>required</td>
    <td>Direct people reached, think number of attendees in a talk.</td>
  </tr>
  <tr>
    <td>metric_indirect</td>
    <td>ndb.IntegerProperty()</td>
    <td>required</td>
    <td>Indirect people reached, think the travel of your social posts.</td>
  </tr>
  <tr>
    <td>metric_trained</td>
    <td>ndb.IntegerProperty()</td>
    <td>required</td>
    <td>Trained people, think number of hits for a tutorial, people at a design sprint.</td>
  </tr>
</table>

<ol start="11">
  <li>The application shall allow a user to remove a support record from a parent activity.</li>
  <li>The application shall allow a user to update a support record on a parent activity.</li>
</ol>

UI / UX Flow:
Step 1: https://app.zeplin.io/project.html#pid=56f2d4d5c0ec67301dd83d12&sid=570dc50eac6c028b1b202f7e

Step 2: https://app.zeplin.io/project.html#pid=56f2d4d5c0ec67301dd83d12&sid=570dc50d5177cd8c1bf4a1e9

Step 3: https://app.zeplin.io/project.html#pid=56f2d4d5c0ec67301dd83d12&sid=577c61de58720b523d32b199

Step 4: https://app.zeplin.io/project.html#pid=56f2d4d5c0ec67301dd83d12&sid=577c6581d8fa9d2f3c6e7444

**Comment by justinribeiro** [comment]
I shuffled reqs 14 and 15 out of this set; the `get metrics` implementation for client callouts can wait until next version (I'll create separate tickets for requested targets).

**Comment by LostInBrittany** [comment]
I've solved the modal problem with dialog (#71) and I've extracted the whole dialog functionality to a `gtt-create-activity` element with the `paper-dialog-behavior` behavior to allow easier positioning and styling  even when it's placed outside its parent dom (to solve the modal bug), but also to make it more _component architecture_-like

**Comment by LostInBrittany** [comment]
First version implemented and working.

Still to do: children records

**Comment by LostInBrittany** [comment]
Done at last!
