### ISSUE TITLE
Vulcanize is failing

### ISSUE THREAD

**Issue by manekinekko** [GoogleDeveloperExperts/experts-app-web#68]
When running the `gulp` command to bundle the app. The vulcanize task fails because of some missing css file. See screenshot:

![image](https://cloud.githubusercontent.com/assets/1699357/16859160/e135b066-4a2c-11e6-8694-0547ac7cce5b.png)

I'm looking at it...

**Comment by manekinekko** [comment]
it seems to come from `Scarygami/discovery-api-elements` in `bower_components/discovery-api-elements/discovery-api-docs.html`. The `discovery-docs-api` element references:

```
<link rel="import" type="css" href="../iron-component-page/iron-component-page.css">
```

**Comment by manekinekko** [comment]
Okay. I fixed the issue. Will send a PR.

**Comment by reicek** [comment]
@manekinekko I see you are working on the v1 app.

This version it's being deprecated, we are currently working on v2 which will launch very soon, it's completely redesigned from the ground up, backend and frontend.

The new version it's a progressive web app and it's extremely fast, easy to use and mobile friendly. 

You can take a peek at the code on the **polymer** branch.

Thank you for you interest and if you wish to help the front-end team, contact me at reicek@hotmail.com and we can see how to enroll you, though we are at the very last development stages.

Next week a team of beta testers will start checking things and after all is perfect we will make the official launch.

Best regards.

**Comment by manekinekko** [comment]
Damn! I thought the last version was already on master. My apologies 😉

**Comment by manekinekko** [comment]
I will check the new branch and let you know

**Comment by reicek** [comment]
No worries.

It wont be on master until it´s ready to be deployed on production.

Best,
