### ISSUE TITLE
GDE User Guide - Doc

### ISSUE THREAD

**Issue by SmokyBob** [GoogleDeveloperExperts/experts-app-web#7]
_From [old repo](https://github.com/maiera/gde-app/issues/206)_
Create a Guide for new GDEs on How to Use the app at it's fullest.

Draft list of features to explain:

How to tag Posts to be recognized by the app
Why edit the activities
Explain Impact formula and why
How to Edit activities
Explain Merge, Trash and Delete
Common Problems/ Report issues
"Only GDEs and Admin can edit data" -> Google + account email <> account.email
Open GitHub issue with debug info from the Chrome Dev Tools

**Comment by reicek** [comment]
Same as #82 

Closing this one
