### ISSUE TITLE
create identity for app

### ISSUE THREAD

**Issue by patt0** [GoogleDeveloperExperts/experts-app-web#72]
Improve user experience on deployment by providing this app a new identity.

**Comment by patt0** [comment]
@justinribeiro @LostInBrittany  added both of you to the project, please pick up the credentials from there.

**Comment by LostInBrittany** [comment]
Hey @patt0 what do you mean by providing a new identity to the app? Using the new client ID in the sign in ?

**Comment by patt0** [comment]
Yes indeed.

**Comment by LostInBrittany** [comment]
Great, then it's done :)
