### ISSUE TITLE
Activity Creation - Country should be dropdown

### ISSUE THREAD

**Issue by mariepatriarche** [GoogleDeveloperExperts/experts-app-web#74]
Country should be a dropdown (to keep consistency in data)

**Comment by patt0** [comment]
Drop down on mobile are not great, autocomplete would be better?

**Comment by mariepatriarche** [comment]
Oh yes anything that improves consistency :) Auto Complete even better indeed!

**Comment by LostInBrittany** [comment]
Good catch, an autocomplete would be nice, yes

**Comment by justinribeiro** [comment]
Merging this into #131
