### ISSUE TITLE
Profile not saving fields is broken

### ISSUE THREAD

**Issue by mariepatriarche** [GoogleDeveloperExperts/experts-app-web#83]
I Tried to set up my profile Info and failed at multiple points:
- No way to save what I edit
- NO way to go to next  page ( guessing there is other pages iwth Profile info)
- When clicking on the Green Check it just deletes what I entered
- There is this odd double line
  ![screen shot 2016-08-17 at 18 41 13](https://cloud.githubusercontent.com/assets/9035600/17745036/9c7c9c26-64aa-11e6-9bf0-ed656514b89e.png)
- Country doesnt have validation ( its in another issue open)

**Comment by patt0** [comment]
Same issue as the other bug raised by Marie.

https://github.com/GoogleDeveloperExperts/experts-app-web/issues/84

Test accounts were not updated to the backend, please try and report.

**Comment by mariepatriarche** [comment]
Still have the exact same issues for Profile (Activity works) after clearing cache, hard reload etc..

**Comment by LostInBrittany** [comment]
The double line is a cosmetic one, as there is a line in not edit mode... But there, it doesn't work, I'll suppress it tonight.

For the not saving problem, is it corrected for you or not yet?

**Comment by mariepatriarche** [comment]
Not yet, even after Patrick reset some stuff and I cleared cache and hard
reloaded

**Comment by LostInBrittany** [comment]
Could you please do a Sign Out (on top right of the page) and a Sign in again? 
If problem is still there, I will ask you for the debug data from your JavaScript console ;)
