### ISSUE TITLE
Activity Creation - Product group should be a preset list

### ISSUE THREAD

**Issue by mariepatriarche** [GoogleDeveloperExperts/experts-app-web#86]
We need some consistency, Product Group should be tags like the Activity Types vs free entry

**Comment by LostInBrittany** [comment]
Yeah, I know, I hand't time last Tuesday, it's in the list of things to do to polish the MVP :)

**Comment by reicek** [comment]
There is no product group for Activity creation @mariepatriarche  , actually I'm wondering why, I wan't to think it's because Experts very often do activities that applies to different products, though I still feel we should report it.

Closing this since it doesn't apply.

**Comment by reicek** [comment]
My bad, consufed sections. Reopening issue.

**Comment by LostInBrittany** [comment]
Please see the new behaviour of the create activity record dialog, it should be better now...

**Comment by LostInBrittany** [comment]
Oups, not yet, still building and deploying ;)
