### ISSUE TITLE
Activity Creation - Unclear flow to add metrics/ URL

### ISSUE THREAD

**Issue by mariepatriarche** [GoogleDeveloperExperts/experts-app-web#87]
Example Flow, trying to think as if I didn't know anything about the App (like the child /parent thing is a bit confusing in the user flow, even knowing about it)
Direct access to my mind:

I am creating a TechTalk activity, I enter basic info and get here
![screenshot 2016-08-18 at 9 21 01 am](https://cloud.githubusercontent.com/assets/9035600/17765268/17331ce0-6525-11e6-9488-b8501a70ca83.png)
# Issue1

Then I see my metrics at zero, I want to add the number of attendees at my talk but
I don't know how to add them but I figure the red button is the only thing I could use so I click it.
# issue2

Now I am asked for a URL.. I am not sure what  URL I should enter: So I add a random URL of the conf or simply text as: (# issue2b):  the  URL does not validate.
# issue3

 I am asked again to add an Activity Group. So I re-enter #TechTalk both in the Activity Group and again in the Activity Type. I am unsure why I am asked twice again (so 3 times total).
# issue4

I enter metrics, I could use some help text to understand what Trained vs reached vs indirectly means.
# issue5

I submit and gets on this screen.
It looks like nothing was saved
![screenshot 2016-08-18 at 9 28 07 am](https://cloud.githubusercontent.com/assets/9035600/17765432/1d1cde38-6526-11e6-9e31-ff6ab8191c24.png)
# issue6

I dont want to redo right now so I just submit what was saved
But the submit button is silent, nothing happens when I click on it

I close with the top right cross, and alleluia My Activity is saved on the main panel BUT
# issue7

The metrics I entered were not saved and nothing shows in my stats
![screenshot 2016-08-18 at 9 29 50 am](https://cloud.githubusercontent.com/assets/9035600/17765472/5bc59206-6526-11e6-9a07-282acf108bab.png)

**Comment by mariepatriarche** [comment]
Actually the metrics are saved but I see them only if I click on the activity itself again

![screenshot 2016-08-18 at 9 32 14 am](https://cloud.githubusercontent.com/assets/9035600/17765536/b85fd13e-6526-11e6-8468-66a0fddc35f7.png)

**Comment by patt0** [comment]
We need to put 0 in the unused metrics for now, if not the call will fail as it expects a number instead of a empty string.

**Comment by LostInBrittany** [comment]
I also find the whole Activity Record - Activity Post flow workflow a bit confusing, yeah...

Any suggestions of a better way to organize the workflow is welcome :)

**Comment by reicek** [comment]
Where did  you got this version @mariepatriarche ? It´s very different from current one.

![image](https://cloud.githubusercontent.com/assets/3601209/17775375/f6dc6f86-6525-11e6-859f-66c976985abe.png)

Please **refresh your web page** before reviewing until RC version it´s announced to avoid confusion.

There are several visual fixes and enhancements coming this week =) 

Closing this issue since it doesn't apply to the current App state.

**Comment by mariepatriarche** [comment]
Here is a quick idea of a Activity Post Workflow

https://docs.google.com/presentation/d/1QP1ppt-_PrG4lKGob9EPwo2HdY820Y_eY9dzijN6ax0/edit#slide=id.g15b96e984e_0_14

Just a suggestion :)
Main idea is to not ask Activity type in Parent Activity but Force adding a
child

**Comment by mariepatriarche** [comment]
I did all couple time, clear cache, hard refresh (cmd+r)
Anything I missed?

Maybe easiest is to add my personal email address in the whitelist to start
fresh?

mariepatriarche@gmail.com

Marie
Request help or Report an Intel bug: go/IntelBug
http://goto.google.com/intelbug

**Comment by reicek** [comment]
My bad, confused sections =/

**Comment by reicek** [comment]
I was looking at the wrong section, totally forgot about this, sorry @mariepatriarche 

Reopening this, we'll be working on this section this week, it needs a lot of fixing ;)

**Comment by reicek** [comment]
I was sure that product tag should be declared somewhere.

I'll be adding it to the activity creating section too. Thanks for this @mariepatriarche

**Comment by mariepatriarche** [comment]
It is but only if you create activity and then edit it again not in the flow

**Comment by LostInBrittany** [comment]
@mariepatriarche Google Drive says I haven't permission to see your doc :(

**Comment by mariepatriarche** [comment]
Fixed :)

You can try now
https://docs.google.com/presentation/d/1QP1ppt-_PrG4lKGob9EPwo2HdY820Y_eY9dzijN6ax0/edit?userstoinvite=horacio.gonzalez@gmail.com&ts=57b61f6f&actionButton=1#slide=id.g15b96e984e_0_37
On Thu, Aug 18, 2016 at 10:51 PM, Horacio Gonzalez <notifications@github.com

**Comment by LostInBrittany** [comment]
Hey, I like it!
Specially the _Beyond numbers_ concept! @patt0 could we add in the model a field for that? I think it can help to make things more useful and user friendly, even if it add some more work in GDE managing program side ;)

**Comment by mariepatriarche** [comment]
See V.2

https://docs.google.com/presentation/d/1QP1ppt-_PrG4lKGob9EPwo2HdY820Y_eY9dzijN6ax0/edit?actionButton=1#slide=id.g15bc39471a_1_41

Tried to merge all recent suggestions
But of course I don't know how it works with current data architecture/ app
infrastructure so eventually totally your call :)

**Comment by LostInBrittany** [comment]
The new workflow is re-done, only thing missing is the **Beyond numbers** field, we can do a new issue for it when/if the backend implements it, what do you think?

So for now, I'm closing this issue...
