### ISSUE TITLE
Child Activity Creation - Confusing between Activity Group & Type

### ISSUE THREAD

**Issue by mariepatriarche** [GoogleDeveloperExperts/experts-app-web#88]
This is a bit confusing , unclear whats the difference between Activity group and Activity Type  and how I should use it

You can have multiple Act. group but only 1 Act. type
![screenshot 2016-08-18 at 11 19 48 am](https://cloud.githubusercontent.com/assets/9035600/17768769/ec7fdba8-6535-11e6-807c-070e9398134f.png)

As discussed with Patrick, one child activity should only have one activity type/group
Act. group should only be there to help you filter/ pick the right activity type) and be clearly marked as such

**Comment by patt0** [comment]
Philosophically my views are

I think each Activity Record should pertain to one and only one type of activity
Its reach which are ActivityPosts are the different channel from which the activity which is recorded in the Activity Record ripples through the physical and digital world.
These can be video's, slides, blog posts, social posts etc ...

**Comment by LostInBrittany** [comment]
The Group is not stored. The only use of the Activity Group buttons is not to show the whole list of possible activity types, i.e.they are only an UX help, maybe not a good one.

About @patt0 views on Records, I agree, I would be happier if the whole Activity Group/Type thin g is raised up to the Record and noty to the Post, it makes more sense to me.

**Comment by reicek** [comment]
This screen shots doesn't reflect the current version of this app @mariepatriarche  . Please refresh your browser windows to get the most recent version of the app.

Several fixes are coming out for Activity Create this week =)

![image](https://cloud.githubusercontent.com/assets/3601209/17775627/1b891df6-6527-11e6-8d90-ea3ab57b968e.png)


Closing this issue.

**Comment by reicek** [comment]
My bad, confused sections =/

**Comment by patt0** [comment]
We could:
1. not select activity type on the ActivityRecord and roll them up from ActivityPost
2. Make an ActivityRecord single type, and define (rename) the type in the ActivityPost to chanel_type which would signify the expression of that activity type.

**Comment by LostInBrittany** [comment]
I prefer solution #2. :)

On Thu, Aug 18, 2016 at 5:37 PM, Patrick Martinent <notifications@github.com

**Comment by patt0** [comment]
If we want to implement, we need to define the channel types, they can be inferred from the link  see https://github.com/GoogleDeveloperExperts/experts-app-backend/issues/30

In the mean time we could use:

video -> reach_trained or reach_indirect
blog >reach_trained
social -> reach_indirect
tech_talk -> reach_direct
workshop -> reach_direct
launchpad -> reach_direct

**Comment by LostInBrittany** [comment]
I like your channel types! If you can implement it in the backend, I can change it very fast in the front.

About the type of reach, I am not sure of the difference between 'direct' and 'trained', or between 'trained' and 'indirect'. In fact, I am not sure of what does 'trained reach' exactly mean...

**Comment by patt0** [comment]
I have it as a commit ready, let me know the moment you want me to push it
... it will break a number of things, and we will have to delete all AR and
AP from the testers, but their is very little there in fact.

Patrick Martinent

**Comment by LostInBrittany** [comment]
If you're ready, we can send now a mail to all testers to explain the
processus, then you can push the commit and I will adapt the frontend.

What do you think ?

On Fri, Aug 19, 2016 at 4:42 AM, Patrick Martinent <notifications@github.com

**Comment by mariepatriarche** [comment]
To make sure I get it, do you mean:
- User enters an Activity details + the activity URL ( but he does not pick
  a category/AT)
- AutoDetect via URL , if medium.com/blabla/androidbalbala
- We would auto-set the ChannelType/Activity Type to blogpost
- User enters  only 1  metric  and  we deduct the kind ((direct /indirect)
  by the auto identified channel_type?

=>  If so, The only issue I see is that I dont think we can deduct "any"
activity by the URL>

How to recognize a tech talk if someone paste slides but another one the
conf website

Note: I also documented the channel_type to Metric in the spreadsheet we
used early on for this project (but cant find the spreadsheet ! :)

**Comment by LostInBrittany** [comment]
As I understand, it means :
1. You create an Activity Record with one or several Activity Types and
   one or several Products Groups that apply to the activity as a whole
2. You create one or several Activity Posts associated to the Activity
   Record. Each Activity Post is a different vector or channel of
   communication for the Activity : blogpost, youtube video, training session,
   and you then choose one Activity Channel by Activity Post.

​

**Comment by patt0** [comment]
pushed, let me know if you have any issues integrating.

Patrick Martinent

**Comment by LostInBrittany** [comment]
OK, I've re-done everything according to the Activity Master / Activity Details paradigm, so I'm closing this one...
