### ISSUE TITLE
Disable Maps Section

### ISSUE THREAD

**Issue by reicek** [GoogleDeveloperExperts/experts-app-web#90]
This feature is potentially getting deprecated =(

**Comment by LostInBrittany** [comment]
Not yet, it's not so easy, you have only eliminated it from the menu, but it is still the default section ;)

**Comment by reicek** [comment]
I did changed the JS @LostInBrittany though didn't removed the code in code in case we want it back later, it's ok so long we keep the HTML just in case =)
