### ISSUE TITLE
GDE logo is missing (also affects Favicon)

### ISSUE THREAD

**Issue by webmaxru** [GoogleDeveloperExperts/experts-app-web#92]
I get 404 for this file: `https://project-6518932152437646681.firebaseapp.com/images/gde-logo.svg`
I see it exists in repo though: `https://github.com/GoogleDeveloperExperts/experts-app-web/blob/polymer/images/gde-logo.svg`

Deployment issue?

**Comment by justinribeiro** [comment]
Looks like a deploy bug.

**Comment by LostInBrittany** [comment]
It doesn't get packed in by the `polymer build` command, I'm going to see why...
