### ISSUE TITLE
Activity type for "Event organizing" is missing

### ISSUE THREAD

**Issue by webmaxru** [GoogleDeveloperExperts/experts-app-web#95]
What if I organize an event (meetup, conference) dedicated fully or partially to Google technologies, but do not speak at it myself

**Comment by justinribeiro** [comment]
@patt0 Can we add this option into the DB (possibly call it `event organize`)?

**Comment by justinribeiro** [comment]
I've added `organize` and sub types to handle this case in the datastore (see screenshot below).

![image](https://cloud.githubusercontent.com/assets/643503/18731024/3fb02c72-800e-11e6-8847-8e0249aa5a99.png)

**Comment by patt0** [comment]
It needs to be added in the DataMigrator spreadsheet where AT 2016 is where
they are documented

Patrick Martinent
