### ISSUE TITLE
Putting in order Activity groups and Activity types

### ISSUE THREAD

**Issue by webmaxru** [GoogleDeveloperExperts/experts-app-web#96]
For now each activity group contains one activity type with the same name. It eliminates the need for 2-level hierarchy at all. Groups/types need to be updated.

**Comment by LostInBrittany** [comment]
I fully agree, groups/types need indeed to be updated, and if each group have only one type, the double hierarchy is bogus.

@patt0 could you give your opinion on this ?

**Comment by patt0** [comment]
I checked the source data and identified a mistake where the tag was set to the group instead of the activity type. I have reuploaded the data and we should be all good.
