### ISSUE TITLE
Context menu in My Activities list doesn't work

### ISSUE THREAD

**Issue by webmaxru** [GoogleDeveloperExperts/experts-app-web#97]
Nothing happens after clicking three vertical dots icon

**Comment by LostInBrittany** [comment]
Indeed, as I'm not sure of what to put there, I took them from the design doc, that didn't add more details, and I kinda forgot to look for meaning... :-/

**Comment by webmaxru** [comment]
I think for now it's enough to have "Delete" action (with confirmation dialog)

**Comment by LostInBrittany** [comment]
It sounds good, I'm adding it tomorrow (a bit late now...)

**Comment by webmaxru** [comment]
Sure :) I'm amazed by what you've already done: @LostInBrittany, @justinribeiro - you are the fastest issue solvers ever :) Great job!

**Comment by reicek** [comment]
They initially planned to put here a pop up menu with edit & delete, but right now to edit you just need to click on the name and just placing a delete icon (plus confirmation) sounds much better for me.

**Comment by LostInBrittany** [comment]
The delete icon is already there, but I haven't wired it.
I will do it tomorrow, as my bug quota for tonight is done (i.e. too sleepy now...)
