### ISSUE TITLE
My profile section doesn't save data after clicking checkmark icon

### ISSUE THREAD

**Issue by webmaxru** [GoogleDeveloperExperts/experts-app-web#98]
In addition: for the Skill - the checkmark icon click doesn't finish editing mode

**Comment by LostInBrittany** [comment]
I'm going to test...

**Comment by LostInBrittany** [comment]
The data is saved on the backend, but the front seems unable to see it., even after a reload. But if you look at the HTTP response for the profile service, data is there... I think something has changed on the API. I'm going to look at it now...
